name: PHPUnit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        php_version: ['8.4', '8.5']
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.php_version }}

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Build the Docker image
      run: make build

    - name: Install dependencies
      run: make install

    - name: Run test suite (except long ones)
      run: make test

    - name: Run test suite (only long ones)
      run: make test-long
